# Generated by Django 3.2 on 2021-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210427_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='password',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
