# Generated by Django 3.2 on 2021-04-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auth_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='password',
        ),
    ]
